project     = "playground-s-11-b7c5bfc4"
region      = "us-central1"
vpc_name    = "base-platform"
subnet_name = "base-vpc"
cidr_range  = "10.2.0.0/16"
environment = "dev"
machine_type = "n2-standard-2"